### ISSUE TITLE
Maximo Core automation

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#1]
Publish content to: https://github.com/IBM/automation-maximo-app-suite

## Definition of Done

- [ ] link to Public Git Repo Epic - https://github.com/IBM/automation-maximo-app-suite
- [ ] link to Public BOM - https://github.com/cloud-native-toolkit/automation-solutions

## Required Automation Modules

- [x] Portworx storage
    - [x] ROKS portworx
    - [x] ROSA portworx
    - [x] ~ARO portworx~
    - [x] Azure IPI portworx
- [x] BAS
- [x] SLS
- [x] Mongo CE
- [x] ~JetStack Cert Manager~ - no longer required
- [x] Maximo Application Suite core
- [x] Storage Class Manager

- [x] Apply storage class manager
    - [x] [BAS](https://github.com/cloud-native-toolkit/terraform-gitops-cp-bas/issues/4)
    - [x] [Mongo CE](https://github.com/cloud-native-toolkit/terraform-gitops-mongo-ce/issues/12)

## Stretch Automation Modules

- [x] [CA Issuer](https://github.com/cloud-native-toolkit/terraform-gitops-ocp-ca-issuer/issues/1)
- [x] [Update Maximo Application Suite to use CA Issuer](https://github.com/cloud-native-toolkit/software-everywhere/issues/102)

- [ ] ODF storage
    - [x] ROKS ODF
    - [ ] ROSA ODF
    - [ ] AWS IPI ?
    - [ ] Azure IPI ODF
    - [ ] Azure ARO ODF
- [ ] Automate license install

## Publish

- [ ] Publish BOM for Maximo Core to Automation Solutions repo
- [ ] Publish generated terraform to [github.com/IBM/automation-maximo-app-suite](https://github.com/IBM/automation-maximo-app-suite)
- [ ] Document detailed installation instructions in README in [github.com/IBM/automation-maximo-app-suite](https://github.com/IBM/automation-maximo-suite)
- [ ] Publish to Seismic
- [ ] Add documentation to the Software Everywhere Documentation Site
- [ ] Create collection in TechZone with videos and demo scripts and link to [github.com/IBM/automation-maximo-app-suite](https://github.com/IBM/automation-maximo-app-suite) in resource

## Supported Platforms

- [x] AWS
- [x] Azure
- [x] IBM Cloud

**Comment by smatthyssen** [comment]
@seansund pls add hyperlinks to the dependencies

**Comment by SatishSNIBM** [comment]
Satish, Need to get MAS Core working on custom domain certificate.

**Comment by smatthyssen** [comment]
@SatishSNIBM please open a new issue and tie it to this Epic.

**Comment by triceam** [comment]
I removed the following from storage class requirements b/c the mongo ce operator should not be including variables required for a `mongoce` instance.  I am repurposing that issue to cleanup incorrect variable assignments.
>     - [ ] [Mongo CE operator](https://github.com/cloud-native-toolkit/terraform-gitops-mongo-ce-operator/issues/8)

**Comment by triceam** [comment]
Removed SLS/storage class manager dependency b/c it is not actually needed per: https://github.com/cloud-native-toolkit/terraform-gitops-cp-sls/issues/11
