### ISSUE TITLE
Cloud Pak for Watson AIOps

### ISSUE THREAD

**Issue by dimallya** [cloud-native-toolkit/software-everywhere#106]
Includes Cloud Pak for Watson AIOps components - AI Manager, Event Manager and Infrastructure Automation 

Publish content to: 

## Definition of Done

- [ ] link to Public Git Repo 
- [ ] link to Public BOM

### Dependencies (name & hyperlink)

**OCP Platform Module**
- [x] [OCP Login](https://github.com/cloud-native-toolkit/terraform-ocp-login.git)
- [x]  [Cloud Pak Catalog Source](https://github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs.git)
- [x] [Sealed Secret](https://github.com/cloud-native-toolkit/terraform-util-sealed-secret-cert.git)
- [x] [GitOps Repository](https://github.com/cloud-native-toolkit/terraform-tools-gitops) 
- [x] [ArgoCD Bootstrap](https://github.com/cloud-native-toolkit/terraform-tools-argocd-bootstrap)
- [x] [OLM](https://github.com/cloud-native-toolkit/terraform-k8s-olm)
- [x] [GitOps Namespace](https://github.com/cloud-native-toolkit/terraform-gitops-namespace)

**CP4WAIOps**
- [ ] [GitOps WAIOps AI Manager](https://github.com/cloud-native-toolkit/terraform-gitops-cp-waiops-aimgr) [#598](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/598)
- [ ] [GitOps WAIOps Event Manager](https://github.com/cloud-native-toolkit/terraform-gitops-cp-waiops-eventmgr)
- [ ] [GitOps WAIOps Infrastructure Automation](https://github.com/cloud-native-toolkit/terraform-gitops-cp-waiops-infra-automation)

### Publish content

- [ ] Generate automation logic and publish to repo 
- [ ] Document installation instructions in README 

### Supported Platforms

- [ ] AWS
- [ ] Azure
- [x] IBM Cloud
