### ISSUE TITLE
Cloud Pak for Integration CP4I

### ISSUE THREAD

**Issue by smatthyssen** [cloud-native-toolkit/software-everywhere#110]
Publish content to: https://github.com/IBM/automation-integration-platform

## Definition of Done

- [ ] link to Public Git Repo 
- [ ] link to Public [BOM](https://github.com/cloud-native-toolkit/automation-solutions/tree/main/boms/software/integration) (need README completed)

### Dependencies (name & hyperlink)

**OCP Platform Module**

- [x] OCP Login
- [x] Cloud Pak Catalog Source
- [x] Sealed Secret
- [x] GitOps Repository
- [x] ArgoCD

**Bootstrap**

**CP4I Operators**

- [x] API Connect Operators [#749](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/749)
- [x] App Connect Operators [#746](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/746)
- [x] MQ Operators [#748](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/748)
- [x] EventStream Operators [#565](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/565)
- [x] PlatformNavigator Operators [#745](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/745)
- [x] DataPower Operators [#706](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/706)
- [x] Aspera Operator [#26](https://github.com/cloud-native-toolkit/automation-modules/issues/26) 
- [ ] Confluent (decided not to do)
- [x] AssetRepository Operator [#649](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/649)
- [x] OperationsDashboard Operator [#648](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/648)

**CP4I Instances**
- [x] PlatformNavigator Instance [#745](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/745)
- [x] App Connect Dashboard Instance[ #635](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/635)
- [x] App Connect Designer Instance [#650](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/650)
- [x] MQ Instance [#585](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/585)
- [x] DataPower Instance [#659](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/659)
- [x] MQ Uniform-Cluster Instance [#567](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/567)
- [x] API Connect Instance [#634](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/634)
- [x] EventStream Instance [#565](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/565)
- [x] Data power Instance [#659](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/659)
- [ ] Aspera [instance](https://github.com/cloud-native-toolkit/automation-modules/issues/27). (Vijay to decide whether to pursue due to lack of GSI use)
- [x] AssetRepo Instance Operator [#649](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/649)
- [x] OperationsDashboard Instance Operator [#648](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/648)

### Publish content

- [ ] Generate automation logic and publish to repo - https://github.com/IBM/automation-integration-platform
- [ ] Document installation instructions in README - https://github.com/IBM/automation-integration-platform

### Supported Platforms

- [x] AWS
- [x] Azure
- [x] IBM Cloud

**Comment by smatthyssen** [comment]
@vksuktha @triceam Here is the new Epic card for CP4I on the public zenhub board

**Comment by smatthyssen** [comment]
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/677

**Comment by smatthyssen** [comment]
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/565

**Comment by smatthyssen** [comment]
@vksuktha @triceam is Confluence a dependency for CP4I?  
If not, let's delete that line from the dependency list.  
If so, is [this](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/376) the module for it?  
If this is not the right module, please add a new issue and update link in the dependency list.

**Comment by smatthyssen** [comment]
@vksuktha @triceam please provide answer to prior question....

**Comment by triceam** [comment]
I do not know dependencies for CP4I

**Comment by smatthyssen** [comment]
@vksuktha please answer questions from 12 days ago and update status and dependency list. Thank you!
