### ISSUE TITLE
Cloud Pak For Security

### ISSUE THREAD

**Issue by dimallya** [cloud-native-toolkit/software-everywhere#119]
Publish content to: (add URL)

## Definition of Done

- [ ] link to Public Git Repo  (add URL)
- [ ] link to Public BOM  (add URL)

### Dependencies (name & hyperlink to Zenhub issue)

**OCP Platform Module**
- [x] [OCP Login](https://github.com/cloud-native-toolkit/terraform-ocp-login.git)
- [x] [Cloud Pak Catalog Source](https://github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs.git)
- [x] [Sealed Secret](https://github.com/cloud-native-toolkit/terraform-util-sealed-secret-cert.git)
- [x] [GitOps Repository](https://github.com/cloud-native-toolkit/terraform-tools-gitops) 
- [x] [ArgoCD Bootstrap](https://github.com/cloud-native-toolkit/terraform-tools-argocd-bootstrap)
- [x] [OLM](https://github.com/cloud-native-toolkit/terraform-k8s-olm)
- [x] [GitOps Namespace](https://github.com/cloud-native-toolkit/terraform-gitops-namespace)

**CP4S**
- [x] [GitOps CP4S](https://github.com/cloud-native-toolkit/terraform-gitops-cp4s) [#757](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/757)

### Publish content

- [ ] Generate automation logic and publish to repo   (add URL)
- [ ] Document installation instructions in README   (add URL)

### Supported Platforms

- [x] AWS
- [x] Azure
- [x] IBM Cloud

**Comment by dimallya** [comment]
Includes CP4S Operator and CP4S Threat Management Instance. 

### Definition of Done
- [ ] link to Public Git Repo Epic
- [ ] link to Public BOM

###  Dependencies (name + hyperlink)

**OCP Platform Module**
- [x] [OCP Login](https://github.com/cloud-native-toolkit/terraform-ocp-login.git)
- [x] [Cloud Pak Catalog Source](https://github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs.git)
- [x] [Sealed Secret](https://github.com/cloud-native-toolkit/terraform-util-sealed-secret-cert.git)
- [x] [GitOps Repository](https://github.com/cloud-native-toolkit/terraform-tools-gitops) 
- [x] [ArgoCD Bootstrap](https://github.com/cloud-native-toolkit/terraform-tools-argocd-bootstrap)
- [x] [OLM](https://github.com/cloud-native-toolkit/terraform-k8s-olm)
- [x] [GitOps Namespace](https://github.com/cloud-native-toolkit/terraform-gitops-namespace)

**CP4S**
- [x] [GitOps CP4S](https://github.com/cloud-native-toolkit/terraform-gitops-cp4s)

**Publish content**
- [ ]  Generate automation logic and publish to repo - 
- [ ]  Document installation instructions in README - 

**Supported Platforms**
- [x]  AWS
- [x]  Azure
- [x]  IBM Cloud

**Delivery Kit**
- [ ] Create Delivery Kit from Template Powerpoint
- [ ]  Business Value
- [ ]  Value to Partner
- [ ]  Delivery Approach
- [ ]  Dependencies
- [ ]  Outcome Value
- [ ]  Place it in Seismic

**Comment by smatthyssen** [comment]
Thanks @dimallya who is working to complete the "Publish content" section?

**Comment by dimallya** [comment]
@smatthyssen Please let me know the overall expectation of "Publish content" task. Is there any template which needs to be followed?

**Comment by dimallya** [comment]
@smatthyssen Figured out that CP4S installation has a dependency on OpenShift serverless-operator and Knative-Serving instance. Hence requested for these modules. Once the modules are ready and included in CP4S BOM, we will start on "Publish content" task.

**Comment by smatthyssen** [comment]
Excellent, thanks Divya!


Take Care,
[signature_2383211786]
Sancia Matthyssen
Manager, Technology Programs
IBM Ecosystem Labs
512.496.8879
***@***.******@***.***>


From: Divya Kamath ***@***.***>
Date: Thursday, April 14, 2022 at 6:27 AM
To: cloud-native-toolkit/software-everywhere ***@***.***>
Cc: Sancia Matthyssen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [cloud-native-toolkit/software-everywhere] Cloud Pak For Security (Issue #119)
@smatthyssen Figured out that CP4S installation has a dependency on OpenShift serverless-operator and Knative-Serving instance. Hence requested for these modules. Once the modules are ready and included in CP4S BOM, we will start on "Publish ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd


@smatthyssen<https://github.com/smatthyssen> Figured out that CP4S installation has a dependency on OpenShift serverless-operator and Knative-Serving instance. Hence requested for these modules. Once the modules are ready and included in CP4S BOM, we will start on "Publish content" task.
