### ISSUE TITLE
DB2 Install - CP4D

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/software-everywhere#150]
Publish content to :

## Definition of Done

Public Git Repo - https://github.com/IBM/automation-data-foundation
- [X] DB2U BOM - https://github.com/IBM/automation-data-foundation/tree/main/310-cloud-pak-for-data-db2uoperator
- [X] DB2OLTP BOM - https://github.com/IBM/automation-data-foundation/tree/main/320-cloud-pak-for-data-db2oltp
- [X] DB2WH BOM - https://github.com/IBM/automation-data-foundation/tree/main/315-cloud-pak-for-data-db2wh

README 
 - [X] CP4D - DB2OLTP : https://github.com/IBM/automation-data-foundation/blob/main/README-DB2OLTP.md
 - [X] CP4D - DB2WH : https://github.com/IBM/automation-data-foundation/blob/main/README-DB2WH.md
 - [X] Expose DB2 : https://github.com/IBM/automation-data-foundation/blob/main/README-DB2-Expose-External.md

### Publish content

- [X] Generate automation logic and publish to repo  
- [X] Document installation instructions in README

### Supported Platforms

- [X] AWS
- [X] Azure
- [X] IBM Cloud

## Required Automation Module

- [x] Terraform-ocp-login
- [x] Terraform-tools-gitops
- [x] Terraform-tools-argocd-bootstrap
- [x] Terraform-gitops-namespace
- [x] Terraform-gitops-pull-secret
- [x] Terraform-gitops-cp-catalogs
- [x] Terraform-gitops-cp-foundational-services
- [x] Terraform-gitops-cp4d-operator
- [x] Terraform-gitops-cp4d-instance
- [X] DB2U Operator
- [X] DB2U OLTP 
- [X] DB2 Warehouse 

**Needed for Maximo**
- [ ] DB2 Instance - Create the DB2 Database.
- [X] DB2 Schema - Create the DB2 Schema  https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/503

**Comment by smatthyssen** [comment]
@balasgit @perrins Turns out this epic is already on the public board.
