### ISSUE TITLE
Publish Maximo to TechZone

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#310]
- [ ] Publish "See It" video content
- [ ] Publish "Learn It" demo content
- [ ] Define "Do It" resources
- [ ] Add TechZone collection to Software Everywhere Seismic page
- [ ] Add TechZone collection to Maximo sales guide
- [ ] Update installation README in TechZone for 101 installer (follow Turbonomic) - Amit
