### ISSUE TITLE
MultiCloud Infrastructure and Storage - Phase 1

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#33]
Publish content to:

- IBM Cloud - [https://github.com/IBM/automation-ibmcloud-infra-openshift](https://github.com/IBM/automation-ibmcloud-infra-openshift)
- AWS - [https://github.com/IBM/automation-aws-infra-openshift](https://github.com/IBM/automation-aws-infra-openshift)
- Azure - [https://github.com/IBM/automation-azure-infra-openshift](https://github.com/IBM/automation-azure-infra-openshift)

## Dependencies (name & hyperlink)

- [x] Quickstart AWS (Terraform) Siva
- [x] Quickstart Azure (Terraform) Rich
- [x] Quickstart IBM (Terraform)
- [x] Quickstart AWS (Ansible)
- [x] Quickstart Azure (Ansible)
- [x] Standard AWS (Ansible)
- [ ] Standard Azure (Ansible) - (Have we decided not to do this?)

## Definition of Done
- [ ] link to Public Git Repo 
- [ ] link to Public BOM

Publish content to the following repos:

#### IBM Repo

- [ ] Document installation instructions in README in [Automation Solutions repo](https://github.com/cloud-native-toolkit/automation-solutions)
- [ ] Generate automation logic from BOM in Automation Solutions repo and publish to repo - https://github.com/IBM/automation-ibmcloud-infra-openshift

#### AWS Repo

- [ ] Document installation instructions in README in [Automation Solutions repo](https://github.com/cloud-native-toolkit/automation-solutions)
- [ ] Generate automation logic from BOM in Automation Solutions repo and publish to repo - https://github.com/IBM/automation-aws-infra-openshift

#### Azure Repo

- [ ] Document installation instructions in README in [Automation Solutions repo](https://github.com/cloud-native-toolkit/automation-solutions)
- [ ] Generate automation logic from BOM in Automation Solutions repo and publish to repo - https://github.com/IBM/automation-azure-infra-openshift

### Supported Platforms

- [x] AWS
- [x]  Azure
- [x]  IBM Cloud

**Comment by smatthyssen** [comment]
@seansund please add hyperlinks to the dependencies
