### ISSUE TITLE
Upgrade gitops modules to use gitops terraform provider

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#496]
The instructions to upgrade a module are provided here - https://ibm.box.com/s/q5s5jwsd8b37k9tbzt73hkmo4tb2tbb8

During this process, two changes will be made:
1. The null_resource block that populates the gitops repo will be replaced with the terraform provider resource
2. The unit test will be updated to use gitea for the gitops repo

### Utilities

Many of these modules are used as submodules

- [x] Gitops module template
- [x] Namespace - pinned to v1.12.2 (provider)
- [x] RBAC - pinned to v1.9.1 (provider)
- [x] SCSS - pinned to v1.4.1
- [x] Service account - pinned to v1.9.0
- [x] Pull secret - pinned to v1.2.0

### Storage

- [x] [IBM ODF](https://github.com/cloud-native-toolkit/terraform-gitops-ibm-odf)
- [x] [IBM Portworx](https://github.com/cloud-native-toolkit/terraform-gitops-ibm-portworx)
- [ ] [IBM Cloud Operator](https://github.com/cloud-native-toolkit/terraform-gitops-ibmcloud-operator)
https://github.com/cloud-native-toolkit/terraform-gitops-ibmcloud-operator/issues/11

### Dev tools

- [x] [Cluster config](https://github.com/cloud-native-toolkit/terraform-gitops-cluster-config)
- [x] [Console Link Job](https://github.com/cloud-native-toolkit/terraform-gitops-console-link-job)
- [x] [Buildah Unprivileged](https://github.com/cloud-native-toolkit/terraform-gitops-buildah-unprivileged)
- [x] [Artifactory](https://github.com/cloud-native-toolkit/terraform-gitops-artifactory)
- [x] [Dashboard](https://github.com/cloud-native-toolkit/terraform-gitops-dashboard)
- [x] [Pact Broker](https://github.com/cloud-native-toolkit/terraform-gitops-pact-broker)
- [x] [Sonarqube](https://github.com/cloud-native-toolkit/terraform-gitops-sonarqube)
- [x] [Swagger Editor](https://github.com/cloud-native-toolkit/terraform-gitops-swagger-editor)
- [x] [Tekton Resources](https://github.com/cloud-native-toolkit/terraform-gitops-tekton-resources)
- [ ] [Image Registry](https://github.com/cloud-native-toolkit/terraform-gitops-image-registry)

### Turbonomic

- [x] [Storage Class](https://github.com/cloud-native-toolkit/terraform-gitops-ocp-storageclass)
- [x] [Turbonomic](https://github.com/cloud-native-toolkit/terraform-gitops-ocp-turbonomic)

### Cloud Pak shared

- [x] [CP Catalogs](https://github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs) cloud-native-toolkit/terraform-gitops-cp-catalogs#23
- [x] [CP Common Services](https://github.com/cloud-native-toolkit/terraform-gitops-cp-foundational-services) https://github.com/cloud-native-toolkit/terraform-gitops-cp-foundational-services/pull/14

### Misc

- [ ] [Service Binding Operator](https://github.com/cloud-native-toolkit/terraform-gitops-service-binding-operator)
- [x] [Global pull secret](https://github.com/cloud-native-toolkit/terraform-gitops-global-pullsecret)
- [x] [Global pull secret sync](https://github.com/cloud-native-toolkit/terraform-gitops-global-pullsecret-synch)

### Data Foundation

- [x] [CP4D Operator](https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator)
- [x] [CP4D Instance](https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-instance)
- [ ] [CP Truststore](https://github.com/cloud-native-toolkit/terraform-gitops-cp-truststore)
- [ ] [CP DB2U Operator](https://github.com/cloud-native-toolkit/terraform-gitops-db2u-operator)
- [ ] [CP DB2 OLTP Service](https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2-oltp)
- [ ] [CP DB2 Warehouse Service](https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2wh-service)
- [ ] [CP DB2](https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2)
- [ ] [CP Data Virtualization](https://github.com/cloud-native-toolkit/terraform-gitops-cp-data-virtualization)
- [ ] [CP Data Virtualization Service](https://github.com/cloud-native-toolkit/terraform-gitops-cp-data-virt-svc)
- [ ] [CP Data Fabric](https://github.com/cloud-native-toolkit/terraform-gitops-cp-data-fabric)
- [ ] [CP Aspera operator](https://github.com/cloud-native-toolkit/terraform-gitops-cp-aspera-operator)
- [ ] [CP Datastage](https://github.com/cloud-native-toolkit/terraform-gitops-cp-datastage)
- [ ] [DB2 Schema](https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2-schema)

### Integration

- [x] [CP Platform Navigator](https://github.com/cloud-native-toolkit/terraform-gitops-cp-platform-navigator) https://github.com/cloud-native-toolkit/terraform-gitops-cp-platform-navigator/pull/19
- [x] [CP AppConnect](https://github.com/cloud-native-toolkit/terraform-gitops-cp-app-connect) https://github.com/cloud-native-toolkit/terraform-gitops-cp-app-connect/pull/18
- [x] [CP ACE Dashboard](https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard) https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard/pull/14
- [x] [CP ACE Designer](https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-designer) https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-designer/pull/10
- [x] [CP Datapower Operator] (github.com/cloud-native-toolkit/terraform-gitops-cp-datapower-operator)
- [x] [CP Datapower] ( https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/issues/18)
- [X] [CP Event Steams operator] (https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/issues/15)
- [x] [CP Event Streams] https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams/issues/22
- [x] [CP MQ] https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/issues/19
- [x] [CP ApiConnect operator]  https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/issues/21
- [x] [CP ApiConnect]  https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/issues/15
- [x] [CP Queue Manager] https://github.com/cloud-native-toolkit/terraform-gitops-cp-queue-manager/issues/16
- [x] [CP MQ Uniform Cluster] https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/issues/11

### AI/ML

- [ ] [CP Watson Studio](https://github.com/cloud-native-toolkit/terraform-gitops-cp-watson-studio)
- [ ] [CP WKC](https://github.com/cloud-native-toolkit/terraform-gitops-cp-wkc)
- [ ] [CP WML](https://github.com/cloud-native-toolkit/terraform-gitops-cp-wml)
- [ ] [CP Watson Assistant](https://github.com/cloud-native-toolkit/terraform-gitops-cp-watson-assistant)
- [ ] [CP Watson Discovery](https://github.com/cloud-native-toolkit/terraform-gitops-cp-watson-discovery)

### Other

- [ ] [OpenLDAP](https://github.com/cloud-native-toolkit/terraform-gitops-openldap)

### Other Cloud Pak

- [ ] [CP4S](https://github.com/cloud-native-toolkit/terraform-gitops-cp4s)
- [ ] [IAF Operator](https://github.com/cloud-native-toolkit/terraform-gitops-cp4ba-iaf-operator)
- [ ] [CP4BA Operator](https://github.com/cloud-native-toolkit/terraform-gitops-cp4ba-ban)
- [ ] [CP Sterling OMS](https://github.com/cloud-native-toolkit/terraform-gitops-cp-sterling-oms)
- [ ] [Kafka Strimzi](https://github.com/cloud-native-toolkit/terraform-gitops-kafka-strimzi)

### Maximo

- [ ] [Mongo CE Operator](https://github.com/cloud-native-toolkit/terraform-gitops-mongo-ce-operator)
- [ ] [Mongo CE](https://github.com/cloud-native-toolkit/terraform-gitops-mongo-ce)
- [ ] [JetStack Cert Manager](https://github.com/cloud-native-toolkit/terraform-gitops-ocp-cert-manager)
- [ ] [Suite License Server](https://github.com/cloud-native-toolkit/terraform-gitops-cp-sls)
- [ ] [CP Maximo](https://github.com/cloud-native-toolkit/terraform-gitops-cp-maximo)
- [ ] [CP MAS Manage](https://github.com/cloud-native-toolkit/terraform-gitops-mas-manage)
- [ ] [MAS JDBC](https://github.com/cloud-native-toolkit/terraform-gitops-mas-jdbc)
- [ ] [MAS Monitor](https://github.com/cloud-native-toolkit/terraform-gitops-mas-monitor)
- [ ] [MAS IoT](https://github.com/cloud-native-toolkit/terraform-gitops-mas-iot)
- [ ] [CP BAS](https://github.com/cloud-native-toolkit/terraform-gitops-cp-bas)
- [ ] [MAS Kafka](https://github.com/cloud-native-toolkit/terraform-gitops-mas-kafka)

### Unreleased (low priority)

- [ ] [CP ODM](https://github.com/cloud-native-toolkit/terraform-gitops-cp-odm)
- [ ] [OCS Operator](https://github.com/cloud-native-toolkit/terraform-gitops-ocs-operator)
- [ ] [CP Filenet](https://github.com/cloud-native-toolkit/terraform-gitops-cp-filenet)
- [ ] [MAS CP4D Config](https://github.com/cloud-native-toolkit/terraform-gitops-mas-cp4d-config)

**Comment by balasgit** [comment]
Working to update this module based on the box note so it gives me idea about changes before i pick Cloud Pak
[ ]  https://github.com/cloud-native-toolkit/terraform-gitops-ibmcloud-operator/issues/11

**Comment by balasgit** [comment]
@seansund - any second opinion on this error since i tried everything to troubleshoot the issues but not much luck. Hence raising hand for help 
 - https://github.com/cloud-native-toolkit/terraform-gitops-ibmcloud-operator/issues/13

**Comment by balasgit** [comment]
All CP4I modules are updated with **Gitops Provider**

1. Here are build errors which are easy to fix but i didn't had a time to troubleshoot except gathered for tracking purpose ONLY.
2. Hence i will look **first thing on Monday morning** 

- https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams/issues/22
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/issues/15
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/issues/19
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/issues/11
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-queue-manager/issues/16
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/issues/18
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/issues/21
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/issues/15

**Comment by balasgit** [comment]
Implemented all the Gitops Provider updates for CP4I modules and here are latest updates wrto testing

**ARGOCD Config Missing**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/issues/18
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/issues/11

**Queue Mgr not found in ROKS**
 - https://github.com/cloud-native-toolkit/terraform-gitops-cp-queue-manager/issues/16

**Main Branch Failing after PR successful**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/issues/15

**Reference to undeclared module**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/issues/21
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/issues/19

**APIConnect instance not coming up** 
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/issues/15

**Destroy Error**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams/issues/22

**Comment by balasgit** [comment]
@seansund @triceam 

Based on the modules.yaml, the modules does have Platform navigator dependency defined.

**Modules.yaml**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-queue-manager/blob/main/module.yaml
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/blob/main/module.yaml

**Common dependency in all modules**
  - source: [github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs.git](http://github.com/cloud-native-toolkit/terraform-gitops-cp-catalogs.git)
 - source: github.com/cloud-native-toolkit/terraform-cp4i-dependency-management.git

**PN Modules.yaml**
- https://github.com/cloud-native-toolkit/terraform-gitops-cp-platform-navigator/blob/main/module.yaml

@mjperrins - FYI

**Comment by balasgit** [comment]
- EventStream operator is updated , tested and released

**Comment by triceam** [comment]
Integration modules moved to separate issue: 
https://github.com/cloud-native-toolkit/software-everywhere/issues/531

Data Foundation modules moved to separate issue:
https://github.com/cloud-native-toolkit/software-everywhere/issues/532
