### ISSUE TITLE
Epic: terraform-gitops-ubi

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/software-everywhere#511]
Publish content to: (add URL)

## Objective

A module should just deploy a pure [ubi image](https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e) (Red Hat Universal Base Image) as a container with [Helm](https://helm.sh/). With the [values.yaml](https://github.com/ibm/ubi-helm/blob/main/charts/ubi-helm/values.yaml) in the Helm chart we can configure [replica count](https://github.com/ibm/ubi-helm/blob/main/charts/ubi-helm/values.yaml#L6) of the pods. The deployed containers are only a basic ubi operating system.
The ubi helm-chart example based on the [ubi-helm repository](https://github.com/thomassuedbroecker/ubi-helm).

Soon it also should provide a command line parameter as input to execute a command during the startup of the UBI container.

The module implementation is already available, but not in the [cloud-native-toolkit](https://github.com/cloud-native-toolkit) org and this is the existing module implementation [terraform-gitops-ubi](https://github.com/Vishal-Ramani/terraform-gitops-ubi) .

This module was developed in the context of operate learning [`lab 4 -create own module`](https://operate.cloudnativetoolkit.dev/learn/iascable/lab4).

## Definition of Done

- [ ] link to Public Git Repo  (add URL)
- [ ] link to Public BOM  (add URL)

### Dependencies (name & hyperlink to Zenhub issue)

- [ ] name and hyperlink to Zenhub issue
- [ ] ....
- [ ] ...

### Publish content

- [ ] Generate automation logic and publish to repo   (add URL)
- [ ] Document installation instructions in README   (add URL)

### Supported Platforms

- [ ] AWS
- [ ] Azure
- [ ] IBM Cloud

FYI: @nheidloff @Vishal-Ramani

**Comment by thomassuedbroecker** [comment]
Related module request: https://github.ibm.com/isv-assets/productivity/issues/88
@seansund 
@Vishal-Ramani

**Comment by nheidloff** [comment]
can we please use this one? https://github.ibm.com/isv-assets/productivity/issues/4
