### ISSUE TITLE
Update CP4I modules to use gitops terraform provider

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#531]
The instructions to upgrade a module are provided here - https://ibm.box.com/s/q5s5jwsd8b37k9tbzt73hkmo4tb2tbb8

During this process, two changes will be made:
1. The null_resource block that populates the gitops repo will be replaced with the terraform provider resource
2. The unit test will be updated to use gitea for the gitops repo

### Integration

- [x] [CP Platform Navigator](https://github.com/cloud-native-toolkit/terraform-gitops-cp-platform-navigator) https://github.com/cloud-native-toolkit/terraform-gitops-cp-platform-navigator/pull/19
- [x] [CP AppConnect](https://github.com/cloud-native-toolkit/terraform-gitops-cp-app-connect) https://github.com/cloud-native-toolkit/terraform-gitops-cp-app-connect/pull/18
- [x] [CP ACE Dashboard](https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard) https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard/pull/14
- [x] [CP ACE Designer](https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-designer) https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-designer/pull/10
- [x] [CP Datapower Operator] (github.com/cloud-native-toolkit/terraform-gitops-cp-datapower-operator)
- [x] [CP Datapower] ( https://github.com/cloud-native-toolkit/terraform-gitops-cp-datapower/issues/18)
- [X] [CP Event Steams operator] (https://github.com/cloud-native-toolkit/terraform-gitops-cp-es-operator/issues/15)
- [x] [CP Event Streams] https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams/issues/22
- [x] [CP MQ] https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/issues/19
- [x] [CP ApiConnect operator]  https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic-operator/issues/21
- [x] [CP ApiConnect]  https://github.com/cloud-native-toolkit/terraform-gitops-cp-apic/issues/15
- [x] [CP Queue Manager] https://github.com/cloud-native-toolkit/terraform-gitops-cp-queue-manager/issues/16
- [x] [CP MQ Uniform Cluster] https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/issues/11

**Comment by triceam** [comment]
Completed:
- Support for gitea (by default)
- Uses the GitOps provider instead of terraform modules
- Updated to use terragrunt for automation between layers

https://github.com/IBM/automation-integration-platform
