### ISSUE TITLE
Epic: Tammy would like to manage Solution Boms from Ascent

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/software-everywhere#552]
Publish content to: (add URL)

## Definition of Done

- [x] Create solution wizard driven from BOMs catalog: https://builder.techzone.ibm.com/solutions/new
- [x] Create solution results in solution.yaml
- [x] Public infra BOMs view data driven from BOMs catalog: https://builder.techzone.ibm.com/boms/infrastructure
- [x] Public software BOMs view data driven from BOMs catalog: https://builder.techzone.ibm.com/boms/software

### Dependencies (name & hyperlink to Zenhub issue)

- [x] Update Wizard to be data driven from BOMs catalog (#378)
- [x] Release all BOMs in automation-solutions (#553)
- [x] Tammy would like to see public infra BOMs content from BOMs catalog (#554)
- [x] Tammy would like to see public software BOMs content from BOMs catalog (#555)
