### ISSUE TITLE
Azure reference architecture modules

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#74]
Modules are needed to implement out reference architectures on Azure: 
https://github.com/cloud-native-toolkit/automation-solutions/tree/main/architectures/azure

Start with the components required for the "Quick Start" architecture, and after that is complete, we can move on the the "Standard" architecture.

We can accomplish this by breaking down the Azure/IPI Cluster automation here:
https://github.com/NoeSamaille/terraform-openshift4-azure

Here's the doc on how to run existing terraform: https://github.com/cloud-native-toolkit/automation-solutions/tree/main/boms/infrastructure/azure/openshift-1-quickstart

We should also use existing patterns for IBM Cloud and AWS as references.

Required Modules:
- [x] [Resource Group](https://github.com/cloud-native-toolkit/terraform-azure-resource-group)
- [x] [Vnet](https://github.com/cloud-native-toolkit/terraform-azure-vnet) (equivalent of VPC)
- [x] [Subnet](https://github.com/cloud-native-toolkit/terraform-azure-subnets) (equivalent of VPC subnet)
- [x] [Load Balancer ](https://github.com/cloud-native-toolkit/terraform-azure-lb) - included in OCP IPI module and ARO module
- [x] Network Security Group (NSG) - included in subnet module
- [ ] Azure automatically allocated public domain name
- [x] [NAT Gateway](https://github.com/cloud-native-toolkit/terraform-azure-nat-gateway)  (#192 )
- [x] [Virtual Machine](https://github.com/cloud-native-toolkit/terraform-azure-vm) (#101 )
- [x] [TLS certificate](https://github.com/cloud-native-toolkit/terraform-azure-acme-certificate) (#217)
- [x] [OpenShift IPI Cluster](https://github.com/cloud-native-toolkit/terraform-azure-ocp-ipi) (Issue #24 )
- [x] [OCP Ingress/API certs](https://github.com/cloud-native-toolkit/terraform-any-ocp-ipi-certs) (Issue #220)
- [ ] OpenShift ARO (using API, without use of CLI)
- [ ] Common Services: Monitoring
- [ ] Common Services: Log Analysis
- [x] [Blob storage](https://github.com/cloud-native-toolkit/terraform-azure-storage-blob) (#173 )
- [x] [SSH Keys / Key Vault](https://github.com/cloud-native-toolkit/terraform-azure-ssh-key) (#167)
- [x] [Bastion Server](https://github.com/cloud-native-toolkit/terraform-azure-vm-bastion) (#208 ) (refer [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host))
- [x] [VPN Server / Point-to-site VPN Gateway](https://github.com/cloud-native-toolkit/terraform-azure-vpn-gateway) (#209 ) (refer [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/point_to_site_vpn_gateway))
- [ ] VNet Peering
- [ ] IasCable BOM

## Definition of Done

- [ ] link to Public Git Repo 
- [ ] link to Public BOM

### Dependencies 

| Module     | Quickstart - IPI | Quickstart - ARO | Standard | Advanced |
|-----------|----------------|------------------|-----------|-----------|
| Public Azure Domain name |? |  |  |  |
| [OCP IPI Cluster](https://github.com/cloud-native-toolkit/terraform-azure-ocp-ipi) | X |  | X | X |
| [TLS Certificate](https://github.com/cloud-native-toolkit/terraform-azure-acme-certificate)  | X |  | X | X |
| [Resource Group](https://github.com/cloud-native-toolkit/terraform-azure-resource-group) |  | X | X | X |
| [Vnet](https://github.com/cloud-native-toolkit/terraform-azure-vnet)  |  | X | X | X |
| [Subnet](https://github.com/cloud-native-toolkit/terraform-azure-subnets)  |  | X | X | X |
| [ARO](https://github.com/cloud-native-toolkit/terraform-azure-aro) |  | X | X | X |
| [Load Balancer ](https://github.com/cloud-native-toolkit/terraform-azure-lb)|  |  | X | X |
| [SSH Keys / Key Vault](https://github.com/cloud-native-toolkit/terraform-azure-ssh-key) | | | X | X | X |
| [Blob storage](https://github.com/cloud-native-toolkit/terraform-azure-storage-blob) | |  | X | X |
| [Virtual Machine](https://github.com/cloud-native-toolkit/terraform-azure-vm) |  |  | X | X |
| [NAT Gateway](https://github.com/cloud-native-toolkit/terraform-azure-nat-gateway) |  |  | X | X |
| [Bastion Server](https://github.com/cloud-native-toolkit/terraform-azure-vm-bastion) |  |  | X | X |
| VPN Server | | | X | X |
| VNet Peering |  |  |  | X |
| VPN Gateway |  |  |  | X |

### Publish content

- [ ] Generate automation logic and publish to repo 
- [ ] Document installation instructions in README 

### Supported Platforms

- [ ] AWS
- [x] Azure
- [ ] IBM Cloud
