### ISSUE TITLE
Turbonomic automation

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#86]
Publish content to: https://github.com/IBM/automation-turbonomic

This offering is simple but powerful all in one setup of turbonomic in an OpenShift cluster, by enabling this to be embedded in all projects will help drive cost reduction for all cloud native solutions

## Definition of Done

- [ ] link to Public Git Repo - https://github.com/IBM/automation-turbonomic
- [ ] link to Public BOM - https://github.com/cloud-native-toolkit/automation-solutions

### Dependencies  (name & hyperlink)

- [x] gitops-ocp-turbonomic
- [x] gitops-bootstrap
- [x] ocp-login
- [x] gitops-repo
- [x] gitops-namespace

### Publish content

- [ ] Generate automation logic and publish to [repo](https://github.com/IBM/automation-turbonomic) 
- [ ] Document installation instructions in [README](https://github.com/IBM/automation-turbonomic) 

### Supported Platforms

- [x] AWS
- [x] Azure
- [x] IBM Cloud

**Comment by smatthyssen** [comment]
@seansund pls add hyperlinks to the dependencies
