### ISSUE TITLE
MultiCloud Infrastructure and Storage - Phase 2

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#88]
Publish content to:

- AWS - [https://github.com/IBM/automation-aws-infra-openshift](https://github.com/IBM/automation-aws-infra-openshift)
- Azure - [https://github.com/IBM/automation-azure-infra-openshift](https://github.com/IBM/automation-azure-infra-openshift)

## Dependencies 

- [ ] Standard AWS (Terraform)
- [ ] Advanced AWS (Terraform)
- [ ] Standard Azure (Terraform)
- [ ] Advanced Azure (Terraform)
- [ ] Standard IBM (Terraform)
- [ ] Advanced IBM (Terraform)

## Definition of Done

Publish content to the following repos:

#### AWS Repo

- [ ] Document installation instructions in README in [Automation Solutions repo](https://github.com/cloud-native-toolkit/automation-solutions)
- [ ] Generate automation logic from BOM in Automation Solutions repo and publish to repo - https://github.com/IBM/automation-aws-infra-openshift

#### Azure Repo

- [ ] Document installation instructions in README in [Automation Solutions repo](https://github.com/cloud-native-toolkit/automation-solutions)
- [ ] Generate automation logic from BOM in Automation Solutions repo and publish to repo - https://github.com/IBM/automation-azure-infra-openshift

### Supported Platforms

- [x] AWS
- [x]  Azure
- [x]  IBM Cloud
