### ISSUE TITLE
Data Fabric automation

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/software-everywhere#89]
Publish content to: github.com/IBM/automation-data-fabric

### Definition of Done
- [ ] link to Public Git Repo
- [ ] link to Public BOM

###  Dependencies 

- [x] [ocp-login]
- [x] [gitops-repo]
- [x] [argocd-bootstrap]
- [x] [gitops-namespace]
- [x] [terraform-gitops-pull-secret]
- [x] [gitops-cp-catalogs]
- [x] [gitops-cp-foundational-services] (https://github.com/cloud-native-toolkit/terraform-gitops-cp-foundational-services)
- [x] [gitops-cp4d-operator] (https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator)
- [x] [gitops-cp4d-instance] (https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-instance)
- [ ] [cp-watson-knowledge-catalog] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/542)
- [x] [cp-watson-studio] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/533)
- [x] [cp-watson-machine-learning] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/588)
- [x] [cp-data-virtualization-service] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/543)
- [x] [cp-data-virtualization] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/556)
- [x] [aws-s3-instance] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/553)
- [x] [aws-s3-bucket] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/554)
- [x] [cp-data-fabric] (https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/566)

**Publish content**
- [ ] Generate automation logic and publish to repo - github.com/IBM/automation-data-fabric
- [ ]  Document installation instructions in README - github.com/IBM/automation-data-fabric

**Supported Platforms**
- [x] AWS
- [ ]  Azure
- [x]  IBM Cloud
