### ISSUE TITLE
Maximo Applications

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/software-everywhere#93]
Publish content to:  [github.com/IBM/automation-maximo-app-suite](github.com/IBM/automation-maximo-app-suite)

This Epic is designed to cover the development work to support the installation of the Maximo applications & industry solutions into a Maximo Application Suite Core Install. Each Story has a break down the the dependencies for each application. The approach will be to complete Manage first and then define the common patterns for each of the applications and industry solutions. 

<img width="694" alt="image" src="https://user-images.githubusercontent.com/102552179/165860149-39ac4b23-1788-44fb-b5f4-f293431cf443.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/102552179/165860208-102c56d8-4375-45bf-a900-6103ef37d721.png">

## Definition of Done

- [ ] link to Public Git [Repo](github.com/IBM/automation-maximo-app-suite) 
- [ ] link to Public BOM

### Dependencies

- [ ] ...DB2 or DB2 Warehouse
- [ ] ....Watson Studio and Watson ML
- [ ] ...Watson Discovery Services (For Assist & Safety)

### Publish content

- [ ] Generate automation logic and publish to repo 
- [ ] Document installation instructions in README 

### Supported Platforms

- [ ] AWS
- [ ] Azure
- [ ] IBM Cloud

**Comment by SatishSNIBM** [comment]
Attaching the db2wh creation in CP4d and schema changes required after database creation
[db2creation_Steps_cp4d_4.0.zip](https://github.com/cloud-native-toolkit/software-everywhere/files/8510460/db2creation_Steps_cp4d_4.0.zip)
[db2Steps_Manage_Create.zip](https://github.com/cloud-native-toolkit/software-everywhere/files/8510468/db2Steps_Manage_Create.zip)
[db2database_create_withincp4d_4.0.zip](https://github.com/cloud-native-toolkit/software-everywhere/files/8598405/db2database_create_withincp4d_4.0.zip)

**Comment by smatthyssen** [comment]
@triceam please fill in dependencies on this epic - or point to the right epic card and close this one.

**Comment by tcskill** [comment]
@triceam @seansund  - Some applications *can* be installed with Maximo Manage. Here is a list of the ones that can.  @seansund this can be done via the design I showed you with Manage that I setup.  I will be adding these one at a time as they can be tested. So add, test, and the next. 

- Health (currently added and being tested)
- Civil Infrastructure (currently added and being tested)
- Aviation
- Spatial
- Nuclear
- Service Provider
- Utilities
- Asset Config Manager
- Workday
- Transportation
- SAP Adapter
- Oracle Adapter
- Oil & Gas
- Health Safety Environment
